<h2>Form Submission </h2>
<form action="">
    <p>First Name:<input type="text"></p>
    <p>Last Name:<input type="text"></p>
    <p>Email:<input type="email"></p>
    <p>Contact:<input type="number"></p>
    <p>Gender:</p>
    <input type="radio">Male
    <input type="radio">Female
    <p>Education:</p>
    <input type="checkbox">UG
    <input type="checkbox">PG
    <p>Address:</p>
    <textarea name="" id="" cols="30" rows="10"></textarea>
    <input type="submit" value="Send">
    
</form>